name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install

      - name: Run semantic-release
        id: release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit and push updated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update CDN links to version $(cat VERSION.txt)"
          branch: main
          file_pattern: |
            README.md
            theme/complete.css
            VERSION.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
